version: "3"
services:
  mongoDB:
    image: mongo
    container_name: pront-mongo-image
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - /data/db

  back:
    image: node:16
    container_name: pront-back-container
    restart: always
    ports:
      - "4001:4000"
    depends_on:
      - mongoDB

  front:
    image: node:16-alpine
    container_name: pront-front-container
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - back

# docker-compose up -d
